updated deps and build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,7 +4,7 @@
 #
 # - it tacks on a version number for use by the individual tools
 # - it supports git and mercurial version#
-# 
+#
 # NB:
 #   o the attempt at decoding dirty repo state for mercurial is
 #     borked. It doesn't know about untracked files
@@ -27,13 +27,10 @@ PWD=`pwd`
 
 Static=0
 Dryrun=0
-Prodver=0.1
+Prodver=""
+Repover=""
 Verbose=0
-
-hostos=$(go env GOHOSTOS)       || exit 1
-hostcpu=$(go env GOHOSTARCH)    || exit 1
-
-[ -f ./version ] && Prodver=$(cat ./version)
+Go=`which go`
 
 die() {
     echo "$Z: $@" 1>&2
@@ -51,39 +48,48 @@ case $BASH_VERSION in
         ;;
 esac
 
+getvcs_version() {
+    local rev=
+    local prodv=
 
-# build a tool that runs on the host - if needed.
-hosttool() {
-    local tool=$1
-    local bindir=$2
-    local src=$3
-
-    local p=$(type -P $tool)
-    if [ -n "$p" ]; then
-        echo $p
-        return 0
+    if [ -d "./.hg" ]; then
+        local xrev=$(hg id --id) || exit 1
+        local brev=${xrev%+}
+        if [ "$brev" != "$xrev" ]; then
+            rev="hg:${brev}-dirty"
+        else
+            rev="hg:${brev}"
+        fi
+        prodv=$(hg log -r "branch(stable) and tag()" -T "{tags}\n" | sort -V | tail -1)
+    elif [ -d "./.git" ]; then
+        local xrev=$(git describe --always --dirty --long --abbrev=12) || exit 1
+        rev="git:$xrev"
+        prodv=$(git tag --list | sort -V | tail -1)
+    else
+        rev="UNKNOWN-VER"
+        warn "Can't find version info"
     fi
 
-    # from here - we want this dir to find all build artifacts
-    PATH=$PATH:$bindir
-    export PATH
+    [ -n "$Prodver" ] && prodv=$Prodver
 
-    p=$bindir/$tool
-    if [ -x $p ]; then
-        echo $p
-        return 0
-    fi
-
-    # build it and stash it in the hostdir
-    echo "Building tool $tool from $src .."
-    $e go get -d      $src || exit 1
-    $e go build -o $p $src || exit 1
-    echo $p
+    echo "$rev $prodv"
     return 0
 }
 
+read -r Repover Prodver <<< $(getvcs_version)
+
 
 usage() {
+    declare -a progv=($Progs)
+    declare n=${#progv[@]}
+    declare pstr=
+
+    for ((i=0; i < n; i++)); do
+        local ent=${progv[$i]}
+        local dir=${ent%%:*}
+        local tool=${ent##*:}
+        pstr=$(printf "$pstr\n\t%s $Prodver $Repover (from ./%s)" $tool $dir)
+    done
 
     cat <<EOF
 $0 - A Go production build tool that adds git-repository information,
@@ -100,9 +106,10 @@ Usage: $0
 Where OS-ARCH denotes one of the valid OS, ARCH combinations supported by 'go'.
 And, PROGS is one or more go programs.
 
-With no arguments, $0 builds: $Progs (source in ./src/)
+With no arguments, $0 builds: $pstr
 
-If ./version is present, its content are used as version number for the binary.
+The repository's latest tag is used as the default version of the software being
+built.
 
 Options:
     -h, --help          Show this help message and quit
@@ -112,16 +119,17 @@ Options:
     -n, --dry-run       Dry-run, don't actually build anything [False]
     -t, --test          Run "go test" on modules named on the command line [False]
     -v, --verbose       Build verbosely (adds "-v" to go tooling) [False]
-    --print-arch        Show the current OS-ARCH for the toolchain and exit [False]
     --vet               Run "go vet" on modules named on the command line [False]
+    --mod               Run "go mod ..." [False]
+    --go=G              Use Go in 'G' [$Go]
     -x                  Run in debug/trace mode [False]
+    --print-arch        Print the target architecture and exit
 EOF
 
     exit 0
 }
 
 host=`uname|tr '[A-Z]' '[a-z]'`
-export GO15VENDOREXPERIMENT=1
 
 declare -A oses
 declare -A cpus
@@ -182,6 +190,7 @@ do
         --arch=*)
             Arch=$ac_optarg
             ;;
+
         -a|--arch)
             ac_prev=Arch
             ;;
@@ -189,6 +198,7 @@ do
         --version=*)
             Prodver=$ac_optarg
             ;;
+
         --test|-t)
             Tool=test
             ;;
@@ -197,9 +207,14 @@ do
             Tool=vet
             ;;
 
+        --mod)
+            Tool=mod
+            ;;
+
         -V|--version)
             ac_prev=Prodver
             ;;
+
         -v|--verbose)
             Verbose=1
             ;;
@@ -214,6 +229,10 @@ do
 
         --debug|-x)
             set -x
+            ;;
+
+        --go-root=*)
+            GoRoot=$ac_optarg
             ;;
 
         --print-arch)
@@ -231,10 +250,80 @@ do
             ;;
   esac
 done
+
 [ $Dryrun  -gt 0 ] && e=echo
 
 # let every error abort
 set -e
+
+# build a tool that runs on the host - if needed.
+hosttool() {
+    local tool=$1
+    local bindir=$2
+    local src=$3
+
+    p=$bindir/$tool
+    if [ -x $p ]; then
+        return 0
+    fi
+
+    local tmpdir=/tmp/$tool.$$
+    mkdir $tmpdir || die "can't make $tmpdir"
+
+    # since go1.20 - install uses env vars to decide where to put
+    # build artifacts. Why are all the google tooling so bloody dev
+    # hostile! WTF is wrong with command line args?!
+    export GOBIN=$bindir
+
+    # build it and stash it in the hostdir
+    echo "Building tool $tool from $src .."
+    (
+       cd $tmpdir
+       $e $Go install  $src@latest || die "can't install $tool"
+    )
+    $e rm -rf  $tmpdir
+
+    return 0
+}
+
+# protobuf gen
+buildproto() {
+    local pbgo=protoc-gen-go
+    local vtgo=protoc-gen-go-vtproto
+    local vtgo_src=github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto
+    local pc
+    local args="$*"
+
+    local pgen=$(type -p protoc)
+    local gogen=$(type -p $pbgo)
+    local vt=$Hostbindir/$vtgo
+
+    [ -z $pgen  ] && die "install protoc tools"
+    [ -z $gogen ] && die "install protoc-gen-go"
+
+    # now install the vtproto generator
+    hosttool $vtgo $Hostbindir $vtgo_src
+
+    for f in $args; do
+        local dn=$(dirname $f)
+        local bn=$(basename $f .proto)
+
+
+        $e $pgen  \
+            --go_out=. --plugin protoc-gen-go=$gogen \
+            --go-vtproto_out=. --plugin protoc-gen-go-vtproto="$vt" \
+            --go-vtproto_opt=features=marshal+unmarshal+size  \
+             $f || die "can't generate protobuf output for $f .."
+    done
+
+    return 0
+}
+
+
+# the rest has to execute in the context of main shell (not funcs)
+
+hostos=$($Go  env GOHOSTOS)      || exit 1
+hostcpu=$($Go env GOHOSTARCH)    || exit 1
 
 # This fragment can't be in a function - since it exports several vars
 if [ -n "$Arch" ]; then
@@ -281,62 +370,29 @@ else
 fi
 
 if [ $Printarch -gt 0 ]; then
-    echo "$cross"
+    echo "$hostos-$hostcpu"
     exit 0
 fi
+
 
 # This is where build outputs go
 Bindir=$PWD/bin/$cross
 Hostbindir=$PWD/bin/$hostos-$hostcpu
+export PATH=$Hostbindir:$PATH
 
 [ -d $Bindir ]     || mkdir -p $Bindir
 [ -d $Hostbindir ] || mkdir -p $Hostbindir
 
-# Get git/hg version info for the build
-if [ -d "./.hg" ]; then
-    xrev=$(hg id --id) || exit 1
-    brev=${xrev%+}
-    if [ "$brev" != "$xrev" ]; then
-        rev="hg:${brev}-dirty"
-    else
-        rev="hg:${brev}"
-    fi
-elif [ -d "./.git" ]; then
-    xrev=$(git describe --always --dirty --long --abbrev=12) || exit 1
-    rev="git:$xrev"
-else
-    rev="UNKNOWN-VER"
-    echo "$0: Can't find version info" 1>&2
-fi
 
 # Do Protobufs if needed
 if [ -n "$Protobufs" ]; then
-    slick=$Hostbindir/protoc-gen-gogoslick
-    slicksrc=github.com/gogo/protobuf/protoc-gen-gogoslick
-    pc=$(type -p protoc)
-
-    [ -z "$pc" ] && die "Need 'protoc' for building .."
-
-    slick=$(hosttool protoc-gen-gogoslick $Hostbindir $slicksrc) || exit 1
-    #if [ ! -f $slick ]; then
-    #   echo "Building $slick .."
-    #   $e go build -o $slick github.com/gogo/protobuf/protoc-gen-gogoslick || exit 1
-    #i
-
-    export PATH=$PATH:$Hostbindir
-
-    for f in $Protobufs; do
-        dn=$(dirname $f)
-        bn=$(basename $f .proto)
-        of=$dn/${bn}.pb.go
-        if [ $f -nt $of ]; then
-            echo "Running $pc .."
-            $e $pc --gogoslick_out=. $f || exit 1
-        fi
-    done
+    set +e
+    buildproto $Protobufs
+    set -e
 fi
 
-repover="main.RepoVersion=$rev"
+# Get git/hg version info for the build
+repover="main.RepoVersion=$Repover"
 prodver="main.ProductVersion=$Prodver"
 date="main.Buildtime=`date -u '+%Y-%m-%dT%H:%M.%SZ'`"
 ldflags="-ldflags \"-X $repover -X $prodver -X $date $ldflags\""
@@ -347,12 +403,17 @@ vflag=""
 case $Tool in
     test)
         set -- $args
-        $e go test $vflag "$@"
+        $e $Go test $vflag "$@"
         ;;
 
     vet)
         set -- $args
-        $e go vet $vflag "$@"
+        $e $Go vet $vflag "$@"
+        ;;
+
+    mod)
+        set -- $args
+        $e $Go mod $vflag "$@"
         ;;
 
     *) # Default is to build programs
@@ -363,9 +424,9 @@ case $Tool in
             all="$@"
         fi
 
-        echo "Building $rev, $cross $msg .."
+        echo "Building $Prodver ($Repover), $cross $msg .."
 
-        for p in $all; do 
+        for p in $all; do
             if echo $p | grep -q ':' ; then
                 out=${p##*:}
                 dir=${p%%:*}
@@ -373,8 +434,15 @@ case $Tool in
                 out=$p
                 dir=$p
             fi
+
+            # Add .exe suffix to out if needed
+            if [ "$GOOS" = "windows" ]; then
+                base=${out%%.exe}
+                out="${base}.exe"
+            fi
+
             echo "   $dir: $out .. "
-            $e eval go build $vflag -o $Bindir/$out $isuffix "$ldflags" ./$dir || exit 1
+            $e eval $Go build $vflag -o $Bindir/$out $isuffix "$ldflags" ./$dir || exit 1
         done
         ;;
 esac
